language: ruby
rvm:
  - ruby-head
  - 2.2.4
  - 2.1
  - 2.0
  - jruby-head
before_install:
- gem update --system
- gem update bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
